config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :movies do
  	collection do
  		get 'search'
  	end
  	resources :reviews, except: [:show, :index]
  end

  root 'movies#index'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  
  searchkick

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, :description, :movie_length, :rating, :director, presence: :true, length: {minimum: 3}
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :rating, :comment, presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_movie, only: [:edit, :update, :show, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@movies = Movie.all().order('created_at DESC')	
	end

	def new
		@movie = current_user.movies.new
	end

	def create
		@movie = current_user.movies.build(movie_params)

		if @movie.save
			redirect_to @movie, notice: 'Movie was successfully created!'
		else
			render 'new'
		end
	end

	def search
		if params[:search].present?
			@movies = Movie.search(params[:search]);
		else
			@movies = Movie.all.order('created_at DESC');
		end
	end

	def show
		@reviews = Review.where(movie_id: @movie)

		if @reviews.any?
			@avg_rating = @reviews.average(:rating)
		else
			@avg_rating = 0
		end
	end

	def update
		@movie = current_user.movies.find(params[:id])
		@movie.update(movie_params)

		if @movie.save
			redirect_to @movie, notice: 'Movie was successfully updated!'
		else
			render 'edit'
		end
	end

	def destroy
		@movie = current_user.movies.find(params[:id])

		@movie.destroy
		
		redirect_to root_path, notice: 'Movie was deleted successfully!'
	end

	private

	def set_movie
		@movie = Movie.find(params[:id])
	end

	def movie_params
		params.require(:movie).permit(:title, :description, :movie_length, :rating, :director, :image)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_movie
	before_action :set_review, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def new
		@review = Review.new
	end

	def create
		@review = current_user.reviews.build(review_params)
		@review.user_id = current_user.id
		@review.movie_id = @movie.id

		if @review.save
			redirect_to edit_movie_review_path(@movie, @review), notice: 'Your review has been created!'
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		@review = current_user.reviews.find(params[:id])
		@review.update(review_params)

		if @review.save
			redirect_to edit_movie_review_path(@movie, @review), notice: 'Changes to your review has been saved!'
		else
			render 'edit'
		end	
	end


	private

	def review_params
		params.require(:review).permit(:rating, :comment)
	end

	def set_movie
		puts params.inspect
		@movie = Movie.find(params[:movie_id])
	end

	def set_review
		@review = Review.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Movie", new_movie_path, class: 'active' %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: 'active' %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mc05MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: 'alert alert-info') %>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
	<p><%= pluralize(@movie.errors.size, 'Error') %> prevented this action from saving.</p>
	<ul>
		<% @movie.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @movie, html: { multipart: true } do |f| %>
	<p>
		<%= f.label :image %><br>
		<%= f.file_field :image, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :movie_length %><br>
		<%= f.text_field :movie_length, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :director %><br>
		<%= f.text_field :director, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :rating %><br>
		<%= f.text_field :rating, class: 'form-control' %>
	</p>
	<p>
		<%= f.submit 'Submit', class: 'btn btn-primary' %>
	</p>
<% end %>

app/views/movies/edit.html.erb
	<div class="row col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Edit Movie</h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
	<h1>Your Favorite Movies Reviewed</h1>
	<p>Hashtag hoodie mumblecore selfies. Authentic keffiyeh leggings Kickstarter, narwhal jean shorts XOXO Vice Austin cardigan. Organic drinking vinegar freegan pickled.</p>
	<p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>
<% end %>

<div class="row">
	<% @movies.each do |movie| %>
	<div class="col-sm-6 col-md-3">
		<div class="thumbnail">
			<%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
		</div>
	</div>
	<% end %>
</div>

app/views/movies/new.html.erb
<div class="container">
	<div class="row col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Movie</h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/movies/search.html.erb
<div class="row">
	<% @movies.each do |movie| %>
	<div class="col-sm-6 col-md-3">
		<div class="thumbnail">
			<%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
		</div>
	</div>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag(@movie.image.url(:medium)) %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td>Title:</td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td>Description:</td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td>Movie Length:</td>
                <td><%= @movie.movie_length %></td>
              </tr>
              <tr>
                <td>Director:</td>
                <td><%= @movie.director %></td>
              </tr>
              <tr>
                <td>Rating:</td>
                <td><%= @movie.rating %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1><%= @movie.title %></h1>
        <p>Average Rating: <span class="star-rating" data-score="<%= @avg_rating %>"></span></p>
        <p><%= @movie.description %></p>
        
        
        <% if @reviews.any? %>
        <%= link_to "Write a Review", new_movie_review_path(@movie), class: 'btn btn-default' %>
        <br><br>
          <h2>User reviews</h2>
            <% @reviews.each do |review| %>
              <div class="reviews">
                <div class="star-rating" data-score="<%= review.rating %>"></div>
                <p><%= review.comment %></p>
                <small>Submitted by <%= review.user.email %>
                <% if review.user == current_user %>
                  <%= link_to "Edit", edit_movie_review_path(@movie, review) %>
                <% end %>
                </small>
              </div>
            <% end %>
        <% else %>
            <h4>No reviews submitted for this movie. <%= link_to "Create one now", new_movie_review_path(@movie) %>.</h4>
        <% end %>

      </div>
    </div>
  </div>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>

	<% if @review.errors.any? %>
		<%= pluralize(@review.errors.size, 'Error') %> prevented this form from saving.
		<ul>
			<% @review.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :rating %>
	<div class="star-rating" data-score="<%= @review.rating %>"></div><br>

	<%= f.label :comment %>
	<%= f.text_area :comment, class: 'form-control' %><br>

	<%= f.submit "Submit", class: 'btn btn-default' %>
	<%= link_to movie_path(@movie) do %>
		<%= f.button "Back to Movie", class: 'btn btn-default' %>
	<% end %>
<% end %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      scoreName: 'review[rating]',
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/edit.html.erb
	<div class="row col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Edit review for: <%= @movie.title %></h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>

app/views/reviews/new.html.erb
	<div class="row col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Write a review for: <%= @movie.title %></h1>
			</div>
			<div class="panel-body">
				<%= render 'form' %>
			</div>
		</div>
	</div>